package com.krrz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePossessionItem<M extends BasePossessionItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setCollection(java.lang.Integer collection) {
		set("collection", collection);
	}
	
	public java.lang.Integer getCollection() {
		return getInt("collection");
	}
	
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	public java.lang.Integer getCount() {
		return getInt("count");
	}
	
	public void setUser(java.lang.Integer user) {
		set("user", user);
	}
	
	public java.lang.Integer getUser() {
		return getInt("user");
	}
	
}

