package com.krrz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBill<M extends BaseBill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUser(java.lang.Integer user) {
		set("user", user);
	}
	
	public java.lang.Integer getUser() {
		return getInt("user");
	}
	
	public void setCheckOutTime(java.util.Date checkOutTime) {
		set("checkOutTime", checkOutTime);
	}
	
	public java.util.Date getCheckOutTime() {
		return getDate("checkOutTime");
	}
	
	public void setTotalMoney(java.lang.Double totalMoney) {
		set("totalMoney", totalMoney);
	}
	
	public java.lang.Double getTotalMoney() {
		return getDouble("totalMoney");
	}
	
}

