package com.krrz.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bill", "id", Bill.class);
		arp.addMapping("collection", "id", Collection.class);
		arp.addMapping("possession_item", "id", PossessionItem.class);
		arp.addMapping("user", "id", User.class);
	}
}


