package com.krrz.common.model;

import com.krrz.common.model.base.BaseBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bill extends BaseBill<Bill> {
	public static final Bill dao = new Bill().dao();
}

