package com.krrz.common.model;

import com.krrz.common.model.base.BaseCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collection extends BaseCollection<Collection> {
	public static final Collection dao = new Collection().dao();
}

