package com.krrz.common.model;

import com.krrz.common.model.base.BasePossessionItem;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PossessionItem extends BasePossessionItem<PossessionItem> {
	public static final PossessionItem dao = new PossessionItem().dao();
}

